const FETCH_REPOS_REQUEST = 'FETCH_REPOS_REQUEST';
const FETCH_REPOS_SUCCESSFUL = 'FETCH_REPOS_SUCCESSFUL';
const FETCH_REPOS_FAILURE = 'FETCH_REPOS_FAILURE';
const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
const FETCH_USER_SUCCESSFUL = 'FETCH_USER_SUCCESSFUL';
const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
const SELECTED_REPO = 'SELECTED_REPO';
const UNSELECTED_REPO = 'UNSELECTED_REPO';
const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'

export {
  FETCH_REPOS_REQUEST,
  FETCH_REPOS_SUCCESSFUL,
  FETCH_REPOS_FAILURE,
  SELECTED_REPO,
  UNSELECTED_REPO,
  FETCH_USER_REQUEST,
  FETCH_USER_SUCCESSFUL,
  FETCH_USER_FAILURE,
  RESET_ERROR_MESSAGE
}
